global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: local

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8889']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: rabbitmq
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: redis
    static_configs:
      - targets: ['redis:6379']
